[package]
name = "cosmic-ext-applet-system-monitor"
version = "0.1.1"
edition = "2021"
authors = ["D-Brox <davidfbg00@gmail.com>"]
description = "System monitor applet for the COSMIC DE"
readme = "README.md"
license = "GPL-3.0"
homepage = "https://github.com/D-Brox/cosmic-ext-applet-system-monitor"
repository = "https://github.com/D-Brox/cosmic-ext-applet-system-monitor.git"
rust-version = "1.80"

[dependencies]
circular-queue = "0.2.6"
i18n-embed-fl = "0.9.1"
open = "5.1.3"
plotters = "0.3.6"
plotters-iced = { git = "https://github.com/D-Brox/plotters-cosmic-iced.git" }
# proc_sys_parser = "0.1.22"
rust-embed = "8.3.0"
serde = "1.0.209"
sysinfo = "0.31.3"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["applet", "tokio", "wayland"]

[dependencies.i18n-embed]
version = "0.15"
features = ["fluent-system", "desktop-requester"]

[package.metadata.deb]
license-file = "LICENSE"
assets = [
    ["target/release/cosmic-ext-applet-system-monitor", "usr/bin/", "755"],
    ["res/dev.DBrox.CosmicSystemMonitor.desktop", "usr/share/applications/", "644"],
    ["res/dev.DBrox.CosmicSystemMonitor.metainfo.xml", "usr/share/metainfo/", "644"],
    ["res/icons/hicolor/scalable/apps/dev.DBrox.CosmicSystemMonitor.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
]
